"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { ShareLink } from "@/types";
import { formatRelativeTime, formatExpiresIn, formatBytes } from "@/lib/utils";
import {
  Share2,
  Search,
  Lock,
  Clock,
  Download,
  Copy,
  Check,
  ExternalLink,
  ShieldAlert,
  RefreshCw,
  Eye,
  CheckCircle2,
  XCircle,
  User,
  FolderOpen,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

export default function AdminSharesPage() {
  const [shares, setShares] = useState<ShareLink[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [copiedToken, setCopiedToken] = useState<string | null>(null);

  const fetchShares = async () => {
    try {
      setLoading(true);
      const res = await fetch("/api/admin/shares");
      const data = await res.json();
      if (data.success && data.shares) {
        setShares(data.shares);
      } else {
        toast.error(data.error || "Could not load share links");
      }
    } catch (err) {
      console.error("Failed to load shares:", err);
      toast.error("Failed to fetch share links");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchShares();
  }, []);

  const handleToggleActive = async (share: ShareLink) => {
    try {
      const nextActive = !share.isActive;
      const res = await fetch("/api/admin/shares", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ shareId: share.id, isActive: nextActive }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success(`Share link ${nextActive ? "activated" : "revoked"}`);
        setShares((prev) =>
          prev.map((s) => (s.id === share.id ? { ...s, isActive: nextActive } : s))
        );
      } else {
        toast.error(data.error || "Failed to update share link");
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to update share link");
    }
  };

  const handleCopy = (token: string) => {
    const fullUrl = `${window.location.origin}/s/${token}`;
    navigator.clipboard.writeText(fullUrl);
    setCopiedToken(token);
    toast.success("Share link copied to clipboard");
    setTimeout(() => setCopiedToken(null), 2000);
  };

  const filteredShares = shares.filter((s) => {
    const q = searchQuery.toLowerCase();
    return (
      s.token.toLowerCase().includes(q) ||
      (s.userEmail && s.userEmail.toLowerCase().includes(q)) ||
      (s.cloudFile?.filename && s.cloudFile.filename.toLowerCase().includes(q))
    );
  });

  return (
    <AdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white flex items-center gap-2.5">
              <span>Active Share Links</span>
              <span className="rounded-md bg-purple-500/10 px-2 py-0.5 text-xs font-semibold text-purple-400 border border-purple-500/20">
                {shares.length} Generated Links
              </span>
            </h1>
            <p className="text-xs sm:text-sm text-zinc-400 mt-1">
              Inspect and control all public download endpoints and tokens generated by users across the system.
            </p>
          </div>

          <Button
            variant="outline"
            size="sm"
            onClick={fetchShares}
            disabled={loading}
            className="gap-2 text-xs self-start sm:self-auto rounded-xl"
          >
            <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin text-purple-400" : ""}`} />
            <span>Refresh</span>
          </Button>
        </div>

        {/* Search */}
        <div className="relative max-w-md">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-500" />
          <Input
            placeholder="Search by token, file, or owner..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-10 text-xs bg-zinc-900/60 border-zinc-800 rounded-xl"
          />
        </div>

        {/* Shares Table */}
        <div className="rounded-3xl border border-zinc-800 bg-zinc-900/60 overflow-hidden shadow-xl">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="border-b border-zinc-800 bg-zinc-950/60 text-[11px] font-semibold uppercase tracking-wider text-zinc-400">
                <tr>
                  <th className="py-3.5 px-4 sm:px-6">Share Token / URL</th>
                  <th className="py-3.5 px-4">Target File</th>
                  <th className="py-3.5 px-4">Owner Profile</th>
                  <th className="py-3.5 px-4">Security</th>
                  <th className="py-3.5 px-4">Downloads</th>
                  <th className="py-3.5 px-4">Expires</th>
                  <th className="py-3.5 px-4 sm:px-6 text-right">Status / Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60">
                {loading ? (
                  <tr>
                    <td colSpan={7} className="py-12 text-center text-zinc-500">
                      <RefreshCw className="h-6 w-6 animate-spin mx-auto text-purple-400 mb-2" />
                      Loading active shares...
                    </td>
                  </tr>
                ) : filteredShares.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="py-12 text-center text-zinc-500">
                      No share links generated yet.
                    </td>
                  </tr>
                ) : (
                  filteredShares.map((share) => (
                    <tr key={share.id} className="hover:bg-zinc-800/40 transition-colors group">
                      {/* Token */}
                      <td className="py-4 px-4 sm:px-6">
                        <div className="flex items-center gap-2">
                          <code className="rounded-lg bg-zinc-950 px-2 py-1 font-mono text-[11px] font-semibold text-purple-400 border border-zinc-800">
                            /s/{share.token}
                          </code>
                          <button
                            onClick={() => handleCopy(share.token)}
                            title="Copy public URL"
                            className="p-1.5 rounded-lg text-zinc-500 hover:text-white hover:bg-zinc-800 transition-colors"
                          >
                            {copiedToken === share.token ? (
                              <Check className="h-3.5 w-3.5 text-emerald-400" />
                            ) : (
                              <Copy className="h-3.5 w-3.5" />
                            )}
                          </button>
                        </div>
                      </td>

                      {/* File */}
                      <td className="py-4 px-4">
                        <div className="min-w-0 max-w-[180px]">
                          <p className="font-semibold text-white truncate">
                            {share.cloudFile?.filename || "Deleted Object"}
                          </p>
                          {share.cloudFile?.size ? (
                            <p className="text-[10px] text-zinc-500">
                              {formatBytes(share.cloudFile.size)}
                            </p>
                          ) : null}
                        </div>
                      </td>

                      {/* Owner with profile link */}
                      <td className="py-4 px-4">
                        <Link
                          href={`/admin/users/${share.userId}`}
                          className="inline-flex items-center gap-1.5 text-zinc-300 hover:text-purple-300 transition-colors group/user"
                          title="Inspect user profile"
                        >
                          <User className="h-3.5 w-3.5 text-zinc-500 group-hover/user:text-purple-400" />
                          <span className="truncate max-w-[130px] text-xs font-semibold">
                            {share.userEmail || "User Profile"}
                          </span>
                        </Link>
                      </td>

                      {/* Security */}
                      <td className="py-4 px-4">
                        {share.passwordProtected ? (
                          <span className="inline-flex items-center gap-1 rounded-md bg-amber-500/10 px-2 py-0.5 text-[10px] font-semibold text-amber-400 border border-amber-500/20">
                            <Lock className="h-3 w-3" />
                            Password
                          </span>
                        ) : (
                          <span className="text-[11px] text-zinc-500">Public</span>
                        )}
                      </td>

                      {/* Downloads count */}
                      <td className="py-4 px-4">
                        <div className="flex items-center gap-1.5 font-semibold text-zinc-200">
                          <Download className="h-3.5 w-3.5 text-sky-400" />
                          <span>
                            {share.downloadCount}{" "}
                            {share.maxDownloads ? `/ ${share.maxDownloads}` : ""}
                          </span>
                        </div>
                      </td>

                      {/* Expiration */}
                      <td className="py-4 px-4 text-[11px] text-zinc-400 whitespace-nowrap">
                        <span className="flex items-center gap-1">
                          <Clock className="h-3 w-3 text-zinc-500" />
                          {formatExpiresIn(share.expiresAt)}
                        </span>
                      </td>

                      {/* Actions */}
                      <td className="py-4 px-4 sm:px-6 text-right">
                        <div className="flex items-center justify-end gap-2">
                          <button
                            onClick={() => handleToggleActive(share)}
                            className={`rounded-lg px-2.5 py-1 text-xs font-semibold transition-all ${
                              share.isActive
                                ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 hover:bg-rose-500/10 hover:text-rose-400 hover:border-rose-500/20"
                                : "bg-rose-500/10 text-rose-400 border border-rose-500/20 hover:bg-emerald-500/10 hover:text-emerald-400 hover:border-emerald-500/20"
                            }`}
                          >
                            {share.isActive ? "Active (Revoke)" : "Revoked (Restore)"}
                          </button>

                          <a
                            href={`/s/${share.token}`}
                            target="_blank"
                            rel="noreferrer"
                            className="p-1.5 rounded-lg text-zinc-500 hover:text-white hover:bg-zinc-800 transition-colors"
                            title="Open Link in New Tab"
                          >
                            <ExternalLink className="h-3.5 w-3.5" />
                          </a>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </AdminLayout>
  );
}
